name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        token: ${{ secrets.PAT }}
    - name: Download binaries
      run: |
        sudo apt-get update
        sudo apt-get install gcc-arm-none-eabi
        sudo apt-get install meson
    - name: Automake
      run: meson setup --cross-file ./compilation_setup.txt build
    - name: Make
      run: |
        cd ./build      # must be executed in the same run, the working directory gets reset for every run
        ninja
    - name: Save compilation results
      uses: actions/upload-artifact@v4
      with:
        name: RTOS
        path: |
          ./build/libRTOS.a
          ./build/RTOS.list
          ./build/RTOS.size
          ./build/libRTOS_no_assert.a
          ./build/RTOS_no_assert.list
          ./build/RTOS_no_assert.size
        # retention-days: 1
    - name: Save compilation results
      uses: actions/upload-artifact@v4
      with:
        name: SampleHelloWorld
        path: |
          ./build/Sample/HelloWorld/main.elf
          ./build/Sample/HelloWorld/main.list
          ./build/Sample/HelloWorld/main.map
          ./build/Sample/HelloWorld/main.size
        # retention-days: 1
    - name: Save compilation results
      uses: actions/upload-artifact@v4
      with:
        name: SampleSleep
        path: |
          ./build/Sample/Sleep/main.elf
          ./build/Sample/Sleep/main.list
          ./build/Sample/Sleep/main.map
          ./build/Sample/Sleep/main.size
        # retention-days: 1
