name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        token: ${{ secrets.PAT }}
    - name: Download binaries
      run: |
        sudo apt-get update
        sudo apt-get install gcc-arm-none-eabi
        sudo apt-get install meson
    - name: Automake
      run: meson setup --cross-file ./compilation_setup.txt build
    - name: Change working directory
      run: |
        ls
        cd ./build
        ls
    - name: Make
      run: ninja
    - name: Save library
      uses: actions/upload-artifact@v4
      with:
        name: libRTOS.a
        path: libRTOS.a
        retention-days: 1
    - name: Save list
      uses: actions/upload-artifact@v4
      with:
        name: RTOS.list
        path: RTOS.list
        retention-days: 1
    - name: Save size
      uses: actions/upload-artifact@v4
      with:
        name: RTOS.size
        path: RTOS.size
        retention-days: 1
